<?php

namespace Hcuv\JobeetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Categories with jobs
     *
     * @return array
     */
    public function getWithJobs()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT c FROM HcuvJobeetBundle:Category c LEFT JOIN c.jobs j WHERE j.expires_at > :date')
            ->setParameter('date', date('Y-m-d H:i:s', time()));

        return $query->getResult();
    }

}
